os:
  - linux

language: php

php:
  - '7.1'

before_script:
  - composer self-update
  - composer install --no-interaction
 

script:
  - phpunit C:\wamp64\www\SOEN341_Website\vendor\autoload.php
  #- jshint resources/assets/js/modules/*

notifications:
  slack:
    on_success: never
    on_fail: always
