language: php
php:
  - '5.6'
  - '7.1'
  - hhvm # on Trusty only
  - nightly

before_install:
  - travis_retry composer self-update
  - composer install

  install: php vendor/vendors.php

script: .\vendor\bin\phpunit --bootstrap vendor\autoload.php test\emailTest