language: php
php:
  - 5.0
  - 5.5
  - 5.6
  - 7.0

before_install:
  - travis_retry composer self-update
  - composer install
script: .\vendor\bin\phpunit --bootstrap vendor\autoload.php test\emailTest