os:
  - linux

language: php

php:
  - '7.1'

before_script:
  - composer self-update
  - composer install --no-interaction



script:
  - vendor/bin/phpunit --coverage-text
  #- phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  - npm run production
  #- jshint resources/assets/js/modules/*

notifications:
  slack:
    on_success: never
    on_fail: always
